### ISSUE TITLE
First exposure metering seems to be wrong

### ISSUE THREAD

**Issue by rightsaidfred99** [vodemn/m3_lightmeter#108]
**Describe the bug**
When I first start the app, maybe I'm being too quick, but I'll get a reading of a scene like this:

F22
2" 
ISO 200

However I hit the button again, without moving the camera, and I'll get the right reading like this

F22
1/30
ISO 200

**To Reproduce**
I can get it to reproduce when first opening the app
OR unlocking the screen and trying it straight away. 

**Expected behavior**
The second metering is always correct. 

**Device:**
 - Pixel 6
 - Android 13 (GraphenOS but that shouldn't make a difference)

**App version**
Latest as of 26.8.23

**Comment by vodemn** [comment]
Seems like a Pixel 6-specific issue.
Reproduced on my Pixel 6 running on stock A13.
Didn't reproduce on Samsung S20+ running A13.

**Comment by vodemn** [comment]
@rightsaidfred99 Were you using a histogram when facing this issue? I gave a bit more testing to this issue and it seems that if the histogram is disabled, it is gone.

**Comment by vodemn** [comment]
Opened an issue in Flutter repo https://github.com/flutter/flutter/issues/134300

**Comment by rightsaidfred99** [comment]
> @rightsaidfred99 Were you using a histogram when facing this issue? I gave a bit more testing to this issue and it seems that if the histogram is disabled, it is gone.

I'll try this. but for the moment I learnt that I just take a few readings and I'll get the right one :)
