### ISSUE TITLE
Remember zoom level

### ISSUE THREAD

**Issue by rightsaidfred99** [vodemn/m3_lightmeter#123]
**Describe the feature or the problem it solves**
It would be great to have an option to remember zoom level

**Describe the solution you'd like**
Every time we open the app, if option is selected, the app will remember zoom level

**Additional context**
On tricky lighting scenes...ie indoors with big windows I often get underexposed images (my fault) because the entire scene is taken in. Often in the field, its tricky under the pump and using one hand to handle phone etc to always zoom etc... 

One less thing to memorize would be great. So in conclusion It would be nice to use the app more of a spotmeter in cases, so having it remember the zoom level , so I can meter for shadows would be handy I think.

**Comment by vodemn** [comment]
@rightsaidfred99 I've updated the description for #44. Will it solve your issue?
If you shoot on a fixed-focus lens, you will be able to set a zoom range where start == end. Therefore you will always have a fixed zoom that corresponds to your lens.

**Comment by rightsaidfred99** [comment]
It's more so if I open the app, I always set a zoom level in the app. Then I shoot and reopen the app - I wish that the app would retain the zoom level last set. 

I know it's minor but I'm mainly using it to meter for shadows, so I always have the app zoomed in rather than the whole scene so it just reduces 1 step in the field I guess.

**Comment by vodemn** [comment]
@rightsaidfred99 It got me thinking recently. If you use zoom to meter for specific spots of the scene, wouldn't this be solved by adding spot metering?

**Comment by rightsaidfred99** [comment]
Yeah, spot metering would be great. I usually get the most accurate negs when using the zone system. 
Outdoors I always use the whole frame when metering but indoors it gets too tricky imo and I have to fall back on metering for shadows.

**Comment by vodemn** [comment]
@rightsaidfred99 After implementing spot metering is this feature still needed?

**Comment by rightsaidfred99** [comment]
I think so, haven't tested in the field but I think this solution will work for very complex scenes. 

Like for an interior, if I just took the base exposure (all zoomed out), light meter would look OK in the live digital preview,  it the film would be underexposed by a stop or two. 

I think now, for such complex scenes, we can just meter for the shadows on the scene which hopefully gives more accurate results. 

I guess I sometimes fall back on the visual digital preview rather than thinking about exposure. Skill issue.

Anyway, that is for the work in this project and this feature.

**Comment by rightsaidfred99** [comment]
Actually looking at this now, on a Pixel 6 the spot meter feature will show the same exposure no matter what when moving the spot around the scene.

**Comment by vodemn** [comment]
> Actually looking at this now, on a Pixel 6

Checked on my Pixel 6, seems fine:

![Screenshot_20231118-214505.png](https://github.com/vodemn/m3_lightmeter/assets/44135514/4cc75778-621e-4806-83d7-6369324f89e1)

![Screenshot_20231118-214455.png](https://github.com/vodemn/m3_lightmeter/assets/44135514/9a704f84-e2bf-451e-a79c-0c84eb447cac)

**Comment by vodemn** [comment]
![Screenshot_20231120-202008.png](https://github.com/vodemn/m3_lightmeter/assets/44135514/e38d6f13-06ae-4248-86f0-37bf44c84e8f)

![Screenshot_20231120-202018.png](https://github.com/vodemn/m3_lightmeter/assets/44135514/1d24947c-ae57-48f6-bfc2-60c3aed1d92d)

**Comment by rightsaidfred99** [comment]
I think I saw the potential "bug" happen when zoomed in? It worked for me ok when not zoomed in. Sorry, I was meaning to edit my post to mention that.

**Comment by vodemn** [comment]
@rightsaidfred99 Closing this one. If you encounter any new bugs, please, create a new issue.
