### ISSUE TITLE
Incorrect Aperture and Shutter Speed reported even when EV is correct.

### ISSUE THREAD

**Issue by ZeroEcks** [vodemn/m3_lightmeter#143]
**Incorrect Aperture and Shutter Speed reported even when EV is correct.**

**To Reproduce**
1. Turn on constant light source
2. Photograph a piece of paper to produce a convenient EV (in our case 9)
3. Compare the list of exposures to another app or mechanical calculator
4. They are different!

**Expected behavior**
For EV 9, my app reports ISO 400, f/2, 1/125. This is not a valid triplet. My camera's mechanical calculator says EV 9, ISO 400, f/2, 1/500. A third party app "Photo Friend" reads the same as my camera's mechanical calculator.

**Screenshots**
![409402045_1580139972790126_8700760786441430558_n](https://github.com/vodemn/m3_lightmeter/assets/1106524/14798a40-f13e-4d0d-bdc7-654b94b6a11d)
![407243537_890780789417130_6191361930251141716_n](https://github.com/vodemn/m3_lightmeter/assets/1106524/f5f65a98-f9d3-4a7e-a2dc-62a5ad13e117)
![411321264_274243811960152_1247337884888665172_n](https://github.com/vodemn/m3_lightmeter/assets/1106524/b2380e04-2086-4abb-a6d4-5eafec74d051)

Here is two screenshots from another friend

![411283828_1494242578103207_5525496879511509310_n](https://github.com/vodemn/m3_lightmeter/assets/1106524/259b62f5-1b46-48be-bf0e-10ef9eee732a)
![403399802_1413778689353120_7719001144438833148_n](https://github.com/vodemn/m3_lightmeter/assets/1106524/3a3f690e-f5c7-4555-ab83-82fe4e6dac7e)

**Device:**
 - Device: Samsung S21 Ultra 512GB
 - OS: Android 13

**App version**
0.15.0 (70045)

**Comment by ZeroEcks** [comment]
Ah, this is an issue between EV_100 and EV_iso (most apps use EV_100, this one uses whatever the current ISO is)

Would it be possible to maybe label it in the app or have a setting to show the EV_100 at the bottom of the screen?

**Comment by vodemn** [comment]
Hello @ZeroEcks 
Thanks for noticing this behaviour.
I think, ISO hint can be integrated to the measuring button, so instead of
```
 EV 
value 
```
it shows EV depending on the setting
```
EV100   /  EViso
value  /   value
```

**Comment by ZeroEcks** [comment]
That would be great, especially for users of cameras with built in calculators like the Pen D3. Thanks for the app :)

**Comment by vodemn** [comment]
@ZeroEcks It occurs to me, that the only accurate values are at the current iso. Like if you are shooting at 400 ISO and then get the results for EV100, your photos will be 2 stop overexposed with EV100 exposure pairs.

Please, correct me if I'm wrong.

**Comment by ZeroEcks** [comment]
Hi, I just saw this feature made it into the app. Made my day! Sorry that I didn't properly articulate why it's useful, but I promise it is for those of us who use the app as a replacement for our cameras calculators since they all operate in ev_100

Thanks again!
