### ISSUE TITLE
Camera freezes after adjusting zoom on Pixel 8 Pro

### ISSUE THREAD

**Issue by vasilescur** [vodemn/m3_lightmeter#146]
**Describe the bug**
A few seconds after adjusting the zoom level, the camera feed freezes and the shutter button hangs forever. Going into settings and back refreshes the camera and fixes the issue-- but also resets zoom to min. Every time the user wants to measure zoomed in, he has to be really fast, frame it, and click the button before it freezes.

**To Reproduce**
1. Create an equipment profile and select an ISO, and film stock (on the paid version of the app, on a pixel 8 pro).
2. Slide the zoom slider to the right.
3. Observe jerky and laggy zooming behavior.
4. Wait one or two seconds, and the camera feed freezes. The zoom slider can still move but it does not unfreeze the camera. Pointing the phone elsewhere also does not change the image preview.
5. Open Settings in the app.
6. Click the Back button.
7. Observe that the zoom slider is reset to minimum (left) and the camera feed is working again.

**Expected behavior**
The zoom slider should move smoothly (except for a lag spike switching between lenses). The camera feed should not freeze when zooming in. If the app detects the camera feed is frozen, it should automatically try to re-initialize the camera, _remembering the same zoom level_.

**Screenshots**
Screenshots won't really illustrate the issue.

**Device:**
 - Device: `Pixel 8 Pro`
 - OS: `Android 14`

**App version**
`0.16.0`

**Comment by vodemn** [comment]
I wasn't able to reproduce this bug on SGS20+, which also has several back cameras. Will try to find a Pixel 8 Pro for further testing.

**Comment by vodemn** [comment]
@vasilescur Does this issue still occur?
