### ISSUE TITLE
In-app purchase doesn't work

### ISSUE THREAD

**Issue by iman1704** [vodemn/m3_lightmeter#156]
**Describe the bug**
Bought and paid for the pro upgrade but it still doesn't unlock pro features in the app

**To Reproduce**
1. Bought pro upgrade through settings menu
2. Paid by google pay/wallet
3. Purchase successful
4. The 'Unlock Pro Features' option is still there and when tapped shows 'error you already own this item'

**Expected behavior**
The pro feature to be immediately unlocked after purchase

**Screenshots**

**Device:**
 - Device: Nothing Phone 1
 - OS: Android 14

**App version**
    0.17.2 (70048)

**Comment by JMYouik** [comment]
same
