### ISSUE TITLE
It doesn't say how much pro costs

### ISSUE THREAD

**Issue by phmayer** [vodemn/m3_lightmeter#171]
as in the title, when clocking on unlock pro, it just says the features and it opens up some google play dialogue.
since i don't want to pay accidentally a price i don't want, im hesitant to click proceed. maybe im not the only person feeling like that.

**Comment by vodemn** [comment]
@phmayer 

The purchase pop up should look like this:

<details>
  <summary>Screenshot</summary>
  
![telegram-cloud-photo-size-2-5276361602695815287-y](https://github.com/vodemn/m3_lightmeter/assets/44135514/c397a5f8-5695-4b0a-a842-3cb637b80bab)
  
</details>

The pop up you see before is not connected with the purchase itself, it is just a review of Google's terms.

**Comment by phmayer** [comment]
@vodemn 
Ahh i see, for me it looks like this:

![Screenshot_20240423-111001.png](https://github.com/vodemn/m3_lightmeter/assets/39195932/9aed238f-fee1-4a04-8a67-ddae9973577d)

i am on the newest version of Android 13 available for my phone.
