### ISSUE TITLE
Buying Pro version without Google Play Store

### ISSUE THREAD

**Issue by LonelyInstantN** [vodemn/m3_lightmeter#179]
Due to Google has no service in my contry. I have no "Leagal" way to add up fund in my Google Pay account (mainly due to google is restricting gift card usage, I bought a gift card but Google said my usage is suspicious and wont let me use, wasnt like this few years ago). So there is no way I can buy a Pro version of this app.

Is there any other way to get a Pro version? Like sponsering through Github? Or directly buy through paypal?

I really like your app and really want to take good use of it. Looking forward to your respond.

**Comment by Heltilo** [comment]
You can with paypal, add you account on googleplay store website (not the app) and it will work.
