### ISSUE TITLE
Translation/UI problems

### ISSUE THREAD

**Issue by stwwwwww** [vodemn/m3_lightmeter#92]
App ver: 0.12.1,Chinese

Device info:POCO F4,Android 13 in MIUI14.0.4

Problems:
1.EV value becomes infinity in ND page
![Screenshot_2023-07-24-16-32-47-978_com vodemn lightmeter](https://github.com/vodemn/m3_lightmeter/assets/75841299/90ce1819-8ab3-4450-87bf-d6ba1c4121c4)
2.Chinese translation in setting page,"分数位"should be "EV步进值"
![Screenshot_2023-07-24-16-32-51-246_com vodemn lightmeter-edit](https://github.com/vodemn/m3_lightmeter/assets/75841299/a401b8ef-a4ce-4a60-b215-4ecdecf63bf2)

**Comment by stwwwwww** [comment]
I'd also like to know if the app can add metering with custom ISO values

**Comment by stwwwwww** [comment]
problem 1 also appears in English

**Comment by ScaredCube** [comment]
I'm sorry. Thank you for correcting the translation error. Changes have been submitted in PR.

**Comment by vodemn** [comment]
1. Fixed in #93 
2. Fixed in https://github.com/vodemn/m3_lightmeter_resources/commit/0715cf98c789d906016308b898219274de7199a2

**Comment by stwwwwww** [comment]
> > I'd also like to know if the app can add metering with custom ISO values
> 
> It can be implemented, but there are some issues to fix with higher priority.

Thank you very much for your work, this will help me a lot as I am going to shoot some low sensitivity film.
Wish you have a good day!
